### ISSUE TITLE
Leaked tracer when wrapping `tinygp`

### ISSUE THREAD

**Issue by femtomc** [dfm/tinygp#139]
Hi @dfm. I'm using your library inside of a larger probabilistic programming library which I'm working on. When I wish to use your library, I'm implementing the following object:

```python
@dataclass
class GaussianProcess(ExactDensity):
    kernel: Any

    def flatten(self):
        return (self.kernel,), ()

    def sample(self, key, X, **kwargs):
        gp = tinygp.GaussianProcess(self.kernel, X)
        y = gp.sample(key, **kwargs)
        return y

    def logpdf(self, y, X, **kwargs):
        gp = tinygp.GaussianProcess(self.kernel, X)
        return gp.log_probability(y)
```

Think of `ExactDensity` here as a dataclass (which is also a `Pytree`) that supports exact sampling and logpdf evaluation.

`kernel` here is a `tinygp.kernels` kernel.

I'm writing models which look approximately like this:

```python
@model
def model(data):
    factor = trace("factor", Uniform)(0.1, 4.0)
    scale = trace("scale", Uniform)(0.1, 5.0)
    kernel_scaled = factor * tinygp.kernels.ExpSquared(scale=scale)
    model = mylib.GaussianProcess(kernel_scaled)
    y = trace("y", model)(data)
    return y
```

However, I'm running into leaked tracers - I've attached an image of the preceding stacktrace. 

<img width="417" alt="image" src="https://user-images.githubusercontent.com/34410036/209617934-925946d2-e5fc-404c-b3d2-b1e7fefdd232.png">

```
UnexpectedTracerError: Encountered an unexpected tracer. A function transformed by JAX had a side effect, allowing 
for a reference to an intermediate value with type float32[] wrapped in a DynamicJaxprTracer to escape the scope of
the transformation.
JAX transformations require that functions explicitly return their outputs, and disallow saving intermediate values
to global state.
------------------------------
```

Now, I'm not sure if you can tell -- but is the idiom I'm using above (e.g. use `tinygp.kernels` inside of a model - and then creating a `tinygp.GaussianProcess` to forward evaluation / sampling, etc) okay? Should I be expecting the above error?

**Comment by femtomc** [comment]
If I change the implementation of my dataclass so that I pass the kernel in (instead of construct it with a kernel instance that is stored in the dataclass) -- it works.

Are kernels pytrees?

**Comment by dfm** [comment]
I think I roughly follow the issue here and I expect there's something more specific about how your library is interacting with these objects that is causing the issue. For example, I put together a simple demo that tries out the basic issues that you seem to be facing and everything works: https://gist.github.com/dfm/1e2e9eb6991ab75a0887f5a5d898679b
See if you can put together a simpler piece of example code that demonstrates the issue and we'll see what we can do!

**Comment by femtomc** [comment]
Thank you! I’ll try and follow your simpler example and see if I can replicate.

**Comment by femtomc** [comment]
@dfm in your gist, you’re not passing values which will become JAX tracers into kernel construction (e.g. with constant values — it works for me too).

**Comment by femtomc** [comment]
I've discovered the error on my end -- in my own Jaxpr transforms, I store models as kwargs in special primitives. I was accidentally storing tracers in the kwargs because of the way I'm constructing GP models.

No issue on your end! Thanks for debugging with me.

**Comment by dfm** [comment]
Not at all - glad you got it sorted!
