### ISSUE TITLE
Spectral Mixture Kernel in tutorial

### ISSUE THREAD

**Issue by zwei-beiner** [dfm/tinygp#142]
I think that the spectral mixture kernel implemented in the tutorial (https://tinygp.readthedocs.io/en/latest/tutorials/kernels.html) does not broadcast correctly over the data when the data points are multidimensional:
Instead of 
```
    def evaluate(self, X1, X2):
        tau = jnp.atleast_1d(jnp.abs(X1 - X2))[..., None]
        return jnp.sum(
            self.weight
            * jnp.prod(
                jnp.exp(-2 * jnp.pi**2 * tau**2 / self.scale**2)
                * jnp.cos(2 * jnp.pi * self.freq * tau),
                axis=-1,
            )
        )
```

we should have 

```
    def evaluate(self, X1, X2):
        tau = jnp.atleast_1d(jnp.abs(X1 - X2))[..., None]
        return jnp.sum(
            self.weight
            * jnp.prod(
                jnp.exp(-2 * jnp.pi**2 * tau**2 / self.scale**2)
                * jnp.cos(2 * jnp.pi * self.freq * tau),
                axis=0, <------------- Change here
            )
        )
```

because we are taking the product over the dimension of the input data (not over the mixture components).

Note that the tutorial only works because the data is one dimensional, in which case the two codes do the same calculation.

Could someone please check? Thank you!

**Comment by dfm** [comment]
Yes - I completely agree that your proposed change seems right! I'd be happy if you want to open a PR making this change.

**Comment by zwei-beiner** [comment]
@dfm I've opened a PR now. The jupyter notebook still has to be re-run because the computation results might change.
