### ISSUE TITLE
Memory leak when evaluating the likelihood of tinygp models

### ISSUE THREAD

**Issue by zairving** [dfm/tinygp#147]
Hi,

I'm experimenting with using this package alongside the nested sampling package [UltraNest](https://johannesbuchner.github.io/UltraNest/index.html), but I've run into a memory leak issue when evaluating the likelihood of my tinygp models.

Package versions:
- JAX: 0.4.1
- tinygp: 0.2.3
- UltraNest: 3.5.7
- Python: 3.11
- Operating System: Ubuntu 22.04

To show what I'm trying to do, I've adapted the [NumPyro example](https://tinygp.readthedocs.io/en/stable/tutorials/modeling.html#sampling-with-numpyro) from the tinygp documentation:
```
import numpy as np
import matplotlib.pyplot as plt
import tinygp
import jax
from ultranest import ReactiveNestedSampler

jax.config.update("jax_enable_x64", True)  # enable double precision in JAX
jax.config.update("jax_platform_name", "cpu")  # force JAX to run on CPU


def kernel(theta):
    return theta[0]**2*tinygp.kernels.ExpSquared(theta[1])*tinygp.kernels.Cosine(theta[2]) + theta[3]**2*tinygp.kernels.Matern32(theta[4])


def build_gp(theta):
    return tinygp.GaussianProcess(kernel(theta), x, diag=yerr**2, mean=theta[5])


def loglike(params):
    return build_gp(params).log_probability(y)


def transform(cube):

    priors = cube.copy()

    # uniform priors for all parameters

    lo, hi = 0, max(y) - min(y)
    priors[0] = cube[0]*(hi - lo) + lo  # ExpSquared amplitude
    priors[3] = cube[3]*(hi - lo) + lo  # Matern-3/2 amplitude

    lo, hi = 1e-1, 1e1
    priors[1] = cube[1]*(hi - lo) + lo  # ExpSquared length-scale
    priors[2] = cube[2]*(hi - lo) + lo  # cosine period

    lo, hi = 1, 100
    priors[4] = cube[4]*(hi - lo) + lo  # Matern-3/2 length-scale

    lo, hi = min(y), max(y)
    priors[5] = cube[5]*(hi - lo) + lo  # mean

    return priors


# generate some data
random = np.random.default_rng(42)
x = np.sort(
    np.append(
        random.uniform(0, 3.8, 28),
        random.uniform(5.5, 10, 18),
    )
)
yerr = random.uniform(0.08, 0.22, len(x))
y = (
    0.2 * (x - 5)
    + np.sin(3 * x + 0.1 * (x - 5) ** 2)
    + yerr * random.normal(size=len(x))
)
true_x = np.linspace(0, 10, 100)
true_y = 0.2 * (true_x - 5) + np.sin(3 * true_x + 0.1 * (true_x - 5) ** 2)


# create figure
fig, ax = plt.subplots(tight_layout=True, dpi=200)

#plot data
ax.errorbar(x, y, yerr, marker="x", capsize=2, color="black", linestyle="None", label="data")
ax.plot(true_x, true_y, "k-", alpha=.5, label="true")


# define sampler
sampler = ReactiveNestedSampler(param_names=["ExpSquared amp", "ExpSquared length-scale", "period",
                                             "Matern-3/2 amplitude", "Matern-3/2 length-scale", "mean"],
                                loglike=loglike,
                                transform=transform,
                                log_dir="/change/me/",
                                resume="resume")

# run sampler
results = sampler.run()
sampler.print_results()

# get medians of posterior distributions
theta = results["posterior"]["median"]

# create GP
gp = build_gp(theta)

# condition GP data
cond_gp = gp.condition(y, true_x).gp
mu, std = cond_gp.mean, np.sqrt(cond_gp.variance)

# plot GP predictive mean and 2 sigma confidence interval
ax.plot(true_x, mu, "r-", label="GP prediction")
ax.fill_between(true_x, mu+2*std, mu-2*std, color="lightgrey", alpha=.5, label="$2 \\sigma$ confidence")


# label plot
ax.set_xlabel("x")
ax.set_ylabel("y")
ax.legend()


plt.show()
```
When running the above code with the System Monitor open, I can see my script's memory usage steadily increasing until one of two things happens: either it consumes all of my system's memory, or the sampler converges. I've found two stopgap solutions to this problem, but neither are particularly satisfactory:

1) Adding a ```@jax.jit``` decorator to ```loglike()``` seems to plug the leak (as well as drastically speeding up the inference process), but this necessarily requires jittable likelihood functions. I'd like to experiment with custom likelihoods which cannot be jitted, so I need another solution in these cases.

2) Using a bash script to automatically restart the script (resuming from ```log_dir```) when the memory usage gets too high. This is problematic because UltraNest doesn't save to ```log_dir``` every iteration, so it's possible that the script will restart before ```log_dir``` gets updated, and then the script will keep restarting without progressing.

I've narrowed this issue down to the ```loglike()``` function because I see the same behaviour when running:
```
import numpy as np
import tinygp
import jax

jax.config.update("jax_enable_x64", True)  # enable double precision in JAX
jax.config.update("jax_platform_name", "cpu")  # force JAX to run on CPU


def kernel(theta):
    return theta[0]**2*tinygp.kernels.ExpSquared(theta[1])*tinygp.kernels.Cosine(theta[2]) + theta[3]**2*tinygp.kernels.Matern32(theta[4])


def build_gp(theta):
    return tinygp.GaussianProcess(kernel(theta), x, diag=yerr**2, mean=theta[5])


def loglike(params):
    return build_gp(params).log_probability(y)


def transform(cube):

    priors = cube.copy()

    # uniform priors for all parameters

    lo, hi = 0, max(y) - min(y)
    priors[0] = cube[0]*(hi - lo) + lo  # ExpSquared amplitude
    priors[3] = cube[3]*(hi - lo) + lo  # Matern-3/2 amplitude

    lo, hi = 1e-1, 1e1
    priors[1] = cube[1]*(hi - lo) + lo  # ExpSquared length-scale
    priors[2] = cube[2]*(hi - lo) + lo  # cosine period

    lo, hi = 1, 100
    priors[4] = cube[4]*(hi - lo) + lo  # Matern-3/2 length-scale

    lo, hi = min(y), max(y)
    priors[5] = cube[5]*(hi - lo) + lo  # mean

    return priors


# generate some data
random = np.random.default_rng(42)
x = np.sort(
    np.append(
        random.uniform(0, 3.8, 28),
        random.uniform(5.5, 10, 18),
    )
)
yerr = random.uniform(0.08, 0.22, len(x))
y = (
    0.2 * (x - 5)
    + np.sin(3 * x + 0.1 * (x - 5) ** 2)
    + yerr * random.normal(size=len(x))
)
true_x = np.linspace(0, 10, 100)
true_y = 0.2 * (true_x - 5) + np.sin(3 * true_x + 0.1 * (true_x - 5) ** 2)

# sample from priors
param_names = ["ExpSquared amp", "ExpSquared length-scale", "period",
                                             "Matern-3/2 amplitude", "Matern-3/2 length-scale", "mean"]
p = [transform(np.random.uniform(size=len(param_names))) for j in range(100)]

# test loglike for memory leak
for i in range(10000):
    L = [loglike(pi) for pi in p]
    print(max(L))
```
Could this issue be related to how I've defined ```loglike```? Or some other issue with my script? I'd really like to be able to solve this issue because I really like this package, but the memory leak makes it unwieldy for my use case (i.e., not jittable likelihood functions).

**Comment by dfm** [comment]
> Adding a jax.jit decorator to loglike() seems to plug the leak (as well as drastically speeding up the inference process), but this necessarily requires jittable likelihood functions. I'd like to experiment with custom likelihoods which cannot be jitted, so I need another solution in these cases.

This is exactly the issue here, and that (`jit`) is the solution! You basically never want to use JAX or tinygp models without jitting them. Can you say more about what you mean by custom likelihoods here or otherwise share an example that fails?

**Comment by zairving** [comment]
Hi Dan,

Thanks for the quick reply! Sure, an example would be the modified likelihood function proposed in equation 13 of [Huebner, et al. 2022](https://ui.adsabs.harvard.edu/abs/2022ApJ...936...17H/abstract), where a data set is decomposed into two outer white noise segments and an inner stochastic segment. Such a likelihood function cannot be jitted because the size of the covariance matrix depends on the parameters of the model. Implementing this function with tinygp models may look something like:
```
def modified_loglike(params):
    # params[0] and params[1] are the beginning and end of the inner (stochastic) segment
    # params[2:n_hyperparams] are the hyperparameters of the covariance function
    # params[2 + n_hyperparams:] are the parameters of the mean function

    # isolate inner subset
    i_in = np.where((x >= params[0]) & (x <= params[1]))
    x_in, y_in, yerr_in = x[i_in], y[i_in], yerr[i_in]
    
    # isolate outer subset
    i_out = np.append(np.where(x < params[0]), np.where(x > params[1]))
    x_out, y_out, yerr_out = x[i_out], y[i_out], yerr[i_out]
    
    # compute residual vector between outer data subset and mean function
    r_out = y_out - jax.vmap(partial(mean_function, params[2+n_hyperparams:]))(x_out)
    
    # compute log likelihood of outer subset
    first_term_out = -.5*np.sum(r_out**2/yerr_out**2)
    second_term_out = -np.sum(np.log(yerr_out))
    third_term_out = -len(x_out)/2*np.log(2*np.pi)
    L_out = (first_term_out + second_term_out + third_term_out)
    
    # return log likelihood of outer subset + log likelihood of GP
    return L_out + build_gp(theta, x_in, yerr_in).log_probability(y_in)
```
Huebner, et al. 2022 use celerite, however, these models are too limited for my needs. Would it be possible to implement such a likelihood function efficiently with tinygp models?

**Comment by dfm** [comment]
As written, that one will definitely be tricky for JAX since the size of the inputs to the GP depend on the inputs. I'm not very familiar with that specific paper, but from your sample code it looks to me like the simplest way to get this to work efficiently in tinygp would be to use a custom kernel like the following (warning: not tested, but should be approximately correct…):

```python
class LocalKernel(tinygp.kernels.Kernel):
    def __init__(self, start, end, base_kernel):
        self.start = start
        self.end = end
        self.base_kernel = base_kernel

    def evaluate(self, X1, X2):
        k0 = self.base_kernel.evaluate(X1, X2)
        in1 = jnp.logical_and(self.start <= X1, X1 <= self.end)
        in2 = jnp.logical_and(self.start <= X2, X2 <= self.end)
        return jnp.where(jnp.logical_and(in1, in2), k0, 0)
```

Which you could then use something like `LocalKernel(params[0], params[1], kernel(params[2:]))`.

This might not be extremely efficient if the typical number of data points that are in the valid range are significantly shorter than your data set. Otherwise, I'd recommend combining something like that with some fixed restricted input range. Hope this helps!

**Comment by zairving** [comment]
Interesting! By setting the covariance matrix elements to be zero outside the range start-stop, the standard likelihood function can be used to evaluate the likelihood of the inner (stochastic) and outer (deterministic) components together. Of course, as you suggest, one downside of this is that the full covariance matrix needs to be inverted, even if most of the elements are zero... Still, slow progress is better than no progress!

Thank you so much for your help!
