### ISSUE TITLE
Updated contributor information needed

### ISSUE THREAD

**Issue by dfm** [dfm/tinygp#152]
I've just added Zenodo metadata file `.zenodo.json` to improve citation tracking: https://github.com/dfm/tinygp/pull/151

This means that we need to manually add contributor information in that file. I'm pinging everyone who has contributed so far to add their information if interested: @yadav-sachin, @theorashid, @jvlatzko, @zwei-beiner, @tkillestein, @andrewfowlie, @elcorto, @tronsgaard

If you'd like to be included in the citation metadata, please leave a comment with your info or open a PR with your information in the following format:

```json
    {
      "orcid": "0000-0002-9328-5652",
      "affiliation": "Center for Computational Astrophysics, Flatiron Institute, New York, NY, USA",
      "name": "Foreman-Mackey, Daniel"
    }
```

Where the [ORCID](https://orcid.org/) field is optional if you don't want to include it.

**Comment by elcorto** [comment]
Hi, thanks for the effort :)

```json
{
  "orcid": "0000-0003-1354-0578",
  "affiliation": "Helmholtz-Zentrum Dresden-Rossendorf e.V.",
  "name": "Schmerler, Steve"
}
```

**Comment by theorashid** [comment]
Sure, although I haven't contributed much. But if you're keeping track of everyone...
```
{
    "affiliation": "School of Public Health, Imperial College London, UK",
    "name": "Rashid, Theo"
  }
```

**Comment by yadav-sachin** [comment]
```    
    {
      "orcid": "0000-0003-0048-1118",
      "affiliation": "Indian Institute of Technology Gandhinagar: Gandhinagar, Gujarat, IN",
      "name": "Yadav, Sachin"
    }
```

**Comment by tkillestein** [comment]
Thanks! 

```json
{
    "orcid": "0000-0002-0440-9597", 
    "name": "Killestein, Thomas",
    "affiliation": "Department of Physics, University of Warwick, Coventry, UK"
}
```

**Comment by andrewfowlie** [comment]
Dan, maybe I will add my name if I make a more substantial contribution :)
thanks for your generous suggestion

**Comment by tronsgaard** [comment]
Thank you, much appreciated!

    {
      "orcid": "0000-0003-1001-0707",
      "affiliation": "Department of Physics and Astronomy, Aarhus University, DK",
      "name": "Tronsgaard, René"
    }
