### ISSUE TITLE
Semiparametric mean function

### ISSUE THREAD

**Issue by scroobiustrip** [dfm/tinygp#160]
Hey there,

I've been checking out TinyGP for the first time, and I'm attempting to port [one of Bill Engels' models](https://bwengals.github.io/mauna-loa-example-2-ice-core-data.html), using the custom semiparametric mean function to predict levels of CO2.

I believe there's an issue with the shapes, where it's returning a `(111, 111)` matrix, when for the model to run I think I need it to be `(111,)`.

The [full notebook](https://colab.research.google.com/drive/1OjajbqSGW7HU2boiHWmV0a2X2CZD5fn5#scrollTo=z7Z_kWOklwN_) can be found here, but I was just wondering if there's any way to get around this, or to reduce the dimensionality of my mean function after calling vmap / partial on it?

I'm building the parameters with this code:

```python
import pandas as pd
import numpy as np

import jax.numpy as jnp
from jax import random, jit, vmap
from functools import partial

def create_changepoints(X, s):
    return (0.5 * (1.0 + jnp.sign(jnp.tile(X.reshape((-1, 1)), (1, len(s))) - s)))

def piecewise_linear(params, X):
    gamma = (-params['s'] * params['delta'])
    growth_rate = (params['k'] + jnp.dot(params['A'], params['delta']))
    offset = (params['m'] + jnp.dot(params['A'], gamma))
    return (offset + growth_rate * X)
    
params = {
    'k': 0.0,
    'm': 0.1,
    'delta': jnp.array([0.05, -0.1, 0.3]),
    's': jnp.array([16, 18, 19]),
    'A': create_changepoints(t_n, s)
}
    
X_grid = np.linspace(0, 1, len(t_n))
model = jax.vmap(partial(piecewise_linear, params))(X_grid)
model.shape # (111, 111)
```

With the model ending up hopefully looking something like:

```python
def numpyro_model(X, X_pred=None, y=None) -> None: 

    jitter = numpyro.sample("jitter", dist.HalfNormal(5.))

    η = numpyro.sample("η", dist.HalfNormal(2.))
    ℓ = numpyro.sample("ℓ", dist.Gamma(4, 2))
    α = numpyro.sample("α", dist.Gamma(3, 1))

    kernel = η**2 * kernels.RationalQuadratic(scale=ℓ, alpha=α)

    ## piecewise linear mean function
    k = numpyro.sample("k", dist.Normal(0., 1.))
    m = numpyro.sample("m", dist.Normal(0., 1.))
    
    with numpyro.plate('changepoints', num_changepoints):
        delta = numpyro.sample("delta", dist.Normal(0., 5.))

    gp = GaussianProcess(
        kernel,
        X, 
        diag=y.std()**2 + jitter, 
        mean=partial(
            piecewise_linear, 
            dict(k=k, m=m, delta=delta, s=s, A=A)
        ),
    )

    if X_pred is None:
        obs = numpyro.sample("obs", gp.numpyro_dist(), obs=y)
        numpyro.deterministic("loc", gp.condition(y, X).gp.loc)
    else:
        numpyro.deterministic(
            "pred",
            gp.condition(y, X_pred).gp.loc
        )
```

However, when I run it I receive the error:

`ValueError: Invalid mean shape: expected ndim = 1, got ndim=2`

Thanks again for the great library, it's been a great, user friendly extension to numpyro for someone who's fairly new to GPs.

**Comment by dfm** [comment]
@scroobiustrip — Thanks for the kind words! I'm happy to explain what's going on here. The problem is that you've pre-computed the linear interpolation matrix for the data points, so you can only evaluate the mean function at the data (and, in fact, you're evaluating it at all the data points regardless of input!). But, the `tinygp` interfaces expects a mean function that can be evaluated everywhere. To do that, I'd use the following:

```python
def dfm_piecewise_linear(params, t):
    a = 0.5 * (1.0 + jnp.sign(t - params["s"]))
    return (params["k"] + a @ params["delta"]) * t + (params["m"] - a @ (params["s"] * params["delta"]))
```

which simply combines your `create_changepoints` and `piecewise_linear` into one function that can be applied at _any_ input time, not just at the data. You'll notice that we no longer use `params["A"]`, so you won't ever need to construct that. Hope this helps!

**Comment by scroobiustrip** [comment]
Ah, that works perfectly thank you! And as well for the added intuition behind how the mean function works (likely would have taken me far too long to figure this out). Many thanks for your help once again! 🙌
