### ISSUE TITLE
Difference in definition between quasisep and stationary kernels; amplitude in one but not another

### ISSUE THREAD

**Issue by nevencaplar** [dfm/tinygp#176]
I notice that there is a difference between the same kernels that are defined in both `kernels.quasisep` and `kernels.stationary`. The kernels that are defined in both ways are:

Matern32 [(quasisep)](https://tinygp.readthedocs.io/en/stable/api/summary/tinygp.kernels.quasisep.Matern32.html) - [stationary](https://tinygp.readthedocs.io/en/stable/api/summary/tinygp.kernels.stationary.Matern32.html)
Matern52 [(quasisep)](https://tinygp.readthedocs.io/en/stable/api/summary/tinygp.kernels.quasisep.Matern52.html) - [stationary](https://tinygp.readthedocs.io/en/stable/api/summary/tinygp.kernels.stationary.Matern52.html)
Cosine [(quasisep)](https://tinygp.readthedocs.io/en/stable/api/summary/tinygp.kernels.quasisep.Cosine.html) - [stationary](https://tinygp.readthedocs.io/en/stable/api/summary/tinygp.kernels.stationary.Cosine.html)
Exp [(quasisep)](https://tinygp.readthedocs.io/en/stable/api/summary/tinygp.kernels.quasisep.Exp.html) - [stationary](https://tinygp.readthedocs.io/en/stable/api/summary/tinygp.kernels.stationary.Exp.html)

The `quasisep` kernels take `sigma`, i.e., amplitude in its definition, while `stationary` kernels do not take `sigma` as input.

Is there a reason for this difference? At the moment it strike me as strange and arbitrary, and it confused me when I was trying to transform my code from `stationary` to `quasisep` definitions. If there is no particular reason for this difference, I suggest to make the definitions consistent.

**Comment by dfm** [comment]
Yes, there is a (perhaps poorly motivated) reason for this! Currently, scalar multiplication of quasiseparable kernels is implemented with [the `Scale` kernel](https://github.com/dfm/tinygp/blob/2bf172d7eddfef24f3e8dbe9cf5ceacbe83dbdba/src/tinygp/kernels/quasisep.py#L300-L306) (not a `Constant` kernel, which doesn't exist), which just scales the `stationary_covariance` matrix. This introduces some computational overhead compared to the `sigma` parameter within the individual kernels.

For your specific point, the `quasisep` kernels don't actually _require_ the `sigma` parameter, so any code implementing a 1D `stationary` model with corresponding kernels in `quasisep` should work without change. For example, I believe that:

```python
from tinygp import kernels

kernel1 = 1.5 * kernels.Matern32(0.5)
kernel2 = 1.5 * kernels.quasisep.Matern32(0.5)
```

should both work and give the same answer, but that

```python
kernel3 = kernels.quasisep.Matern32(0.5, sigma=sqrt(1.5))
```

would give (very slightly!) better performance.

I'm not too worried about making porting in the other direction work seamlessly (i.e. supporting `sigma` for the base kernels), but it would certianly be possible, and I'd be happy to review such a PR!

**Comment by nevencaplar** [comment]
Ok, thank you, that makes sense. 

I have an alternative proposal that would still alleviate the initial confusion that I had when implementing  code with `quasisep` kernels, while probably being easier to implement.

Documentation at the moment does not mention that `sigma` is optional in `quasisep` kernels. I believe it would be more useful if it would be indicated that the parameter is optional, as in this [example of the documentation](https://tinygp.readthedocs.io/en/stable/api/summary/tinygp.GaussianProcess.html?highlight=optional). What do you think @dfm?

**Comment by dfm** [comment]
I think that would be great! And perhaps we can mention the performance point there too. Would you be up for opening such a PR?
