### ISSUE TITLE
multivariate GP and constant kernel

### ISSUE THREAD

**Issue by pilchat** [dfm/tinygp#192]
Hi @dfm ,

I'm trying to adapt your multivariate GP example (https://tinygp.readthedocs.io/en/latest/tutorials/multivariate.html) to my case: I would like to have a 2D GP with two independent amplitudes. I define a 'params' dictionary where each field is a 2-element array, and use it to build the the GP as:

`kernel = kernels.Constant(params["log_amp"]) * kernels.ExpSquared(scale=jnp.exp(params["log_lambda"])) * kernels.ExpSineSquared(scale=params["P"],gamma=params["Gamma"])`

When I run you example code, the line
`uncorr_gp = train_gp(2, build_gp_uncorr)`
raises the error
`ValueError: The value of a constant kernel must be a scalar`

After some playing around, I have the feeling that the Constant kernel does not support multidimensionality. Is it correct? How can I fix it?

**Comment by dfm** [comment]
I'm not really sure what you mean by "two independent amplitudes" here. Can you write out what you mean clearly as an equation?

One option could be that you want two separate kernels that operate independently on each dimension. In that case, you could use [the `Subspace` transform](https://tinygp.readthedocs.io/en/latest/api/summary/tinygp.transforms.Subspace.html):

```python
from tinygp import kernels, transforms

base_kernel = kernels.ExpSquared(scale=jnp.exp(params["log_lambda"])) * kernels.ExpSineSquared(scale=params["P"],gamma=params["Gamma"])

kernel1 = transforms.Subspace(0, jnp.exp(params["log_amp"][0]) * base_kernel)
kernel2 = transforms.Subspace(1, jnp.exp(params["log_amp"][1]) * base_kernel)

kernel = kernel1 + kernel2
```

**Comment by pilchat** [comment]
Hi Dave,

this answers my question, thanks a lot!
