### ISSUE TITLE
Numerical instabilities in Cholesky decomposition with quasisep kernels

### ISSUE THREAD

**Issue by nevencaplar** [dfm/tinygp#203]
When fitting some relatively simple models (pure quasisep exponential kernel) sometimes I get unphysical results; The parameters are completely unreasonable, but the final results claims good likelihood. I think the origin is overflows and instability in the [Cholesky decomposition for quasisep kernels](https://github.com/dfm/tinygp/blob/89880adc55d56ed0df15324dd0dafc9ea726d155/src/tinygp/solvers/quasisep/core.py#L546).
Unfortunately, I was not able to produce a minimal example that would prove that definitely. I am especially suspicious of [this line](https://github.com/dfm/tinygp/blob/89880adc55d56ed0df15324dd0dafc9ea726d155/src/tinygp/solvers/quasisep/core.py#L558C12-L558C45), but again I am not able to prove it at this stage.

The best I have manged to do is to have here a notebook that shows that the decomposition produces different results for parameters that differ in their 15th digit.
https://colab.research.google.com/drive/1mL81GdAFrNyebJhMZ32dNpenhqkvO48c?usp=sharing

I see that direct solver uses jax defined cholesky decomposition. Wouldnt that be an option here as well? I pressume that the transformation in and out of `LowerTriQSM` is a complication?

@dfm I would love to hear your thoughts.

**Comment by dfm** [comment]
The problem with your notebook there is that `10**28.407914772784345 == 2.558083831813623e+28` - good luck getting any numerical stability when that's the amplitude of your GP!

**Comment by dfm** [comment]
> I see that direct solver uses jax defined cholesky decomposition. Wouldnt that be an option here as well? I pressume that the transformation in and out of LowerTriQSM is a complication?

The JAX cholesky decomposition scales as N^3. If you're datasets are small enough that's ok, then go ahead and use the direct solver, but it'll be orders of magnitude slower for most use cases.

**Comment by nevencaplar** [comment]
> The problem with your notebook there is that `10**28.407914772784345 == 2.558083831813623e+28` - good luck getting any numerical stability when that's the amplitude of your GP!

Right, these parameters are best parameters from my fitting procedure (this particular lightcurve, with exp kernel, under certain assumptions). I did not pick 10**28 on my own :). I can manually remove the solutions that fall in this part of parameter space; but at this point the code is silently producing wrong results. At minimum I would advocate for it to warn/fail loudly.

**Comment by dfm** [comment]
I believe that you'll find similar issues with any other linear algebra library, including the JAX cholesky decomposition, where you'll get silent failures for some pathological matrices. I don't think it's straightforward to define the range of parameters where numerical stability is a problem in general, but it would be easy for you to put sensible bounds in your analysis! I'd recommend always putting reasonable bounds in your problem - these algorithms work over many orders of magnitude, but you're asking a lot here.

**Comment by nevencaplar** [comment]
Ok, I will close the issue given your input. I am still unhappy :) 

(jax scipy optimizer that performs speed wise best for me only takes BFGS, so it is not possible to put constraints; that is how I discovered this problem - but as mentioned I can get around that otherwise). 

Thank you for your help, incredibly valuable as always!!!

**Comment by dfm** [comment]
To use bounded parameters with that optimizer, you can reparameterize using something like a sigmoid function so that the input "parameter" has infinite support but the parameter you use in your model has finite support. I'm not at my computer, but I'm happy to provide more details later if that's not clear!
