### ISSUE TITLE
Double precision required for /tutorials/quickstart.html

### ISSUE THREAD

**Issue by krosenfeld-IDM** [dfm/tinygp#24]
## Description
As set in the binder and collab notebooks, double precision (`jax.config.update("jax_enable_x64")`) seems to be required to get the [quickstart example](https://tinygp.readthedocs.io/en/latest/tutorials/quickstart.html) to run.
Otherwise, if I follow along directly from the quickstart page  the log-likelihood evaluantes to `nan`. It might be helpful for people following the tutorial page (and not in the binder/collab notebook) to include that configuration step. 

## Issue:

```
import jax
import jax.numpy as jnp

from tinygp import kernels, transforms, GaussianProcess

def build_gp(theta, X):
    mean = theta[-1]

    # We want most of out parameters to be positive so we take the `exp` here
    # Note that we're using `jnp` instead of `np`
    theta = jnp.exp(theta[:-1])

    # Construct the kernel by multiplying and adding `Kernel` objects
    k1 = theta[0] ** 2 * kernels.ExpSquared(theta[1])
    k2 = (
        theta[2] ** 2
        * kernels.ExpSquared(theta[3])
        * kernels.ExpSineSquared(period=theta[4], gamma=theta[5])
    )
    k3 = theta[6] ** 2 * kernels.RationalQuadratic(
        alpha=theta[7], scale=theta[8]
    )
    k4 = theta[9] ** 2 * kernels.ExpSquared(theta[10])
    kernel = k1 + k2 + k3 + k4

    return GaussianProcess(kernel, X, diag=theta[11] ** 2, mean=mean)


def neg_log_likelihood(theta, X, y):
    gp = build_gp(theta, X)
    return -gp.condition(y)


# These are the parameters from R&W
theta_init = np.append(
    np.log(
        [66.0, 67.0, 2.4, 90.0, 1.0, 4.3, 0.66, 1.2, 0.78, 0.18, 1.6, 0.19]
    ),
    340.0,
)

# `jax` can be used to differentiate functions, and also note that we're calling
# `jax.jit` for the best performance.
obj = jax.jit(jax.value_and_grad(neg_log_likelihood))

print(f"Initial negative log likelihood: {obj(theta_init, t, y)[0]}")
print(
    f"Gradient of the negative log likelihood, wrt the parameters:\n{obj(theta_init, t, y)[1]}"
)

```
returned
```
Initial negative log likelihood: nan
Gradient of the negative log likelihood, wrt the parameters:
[nan nan nan nan nan nan nan nan nan nan nan nan nan]
```

## System
Conda on Windows Enterprise

**Comment by dfm** [comment]
Thanks for this and good catch! I struggled trying to decide where to put that, but I think you're absolutely right that it should be more explicit.

That being said, I think it would be good to make sure that this works in float32 as well, and I'm surprised that it doesn't. I'll look into all of this shortly. Thanks again for the report.

**Comment by dfm** [comment]
I handled this over in #25 by updating most of the tutorials to actually work without x64 mode and then explicitly enabling it when necessary. Thanks again for your help!
