### ISSUE TITLE
Feature Request: Derivative observations

### ISSUE THREAD

**Issue by cranmer** [dfm/tinygp#38]
It's possible that I missed it, but it would be great if tinyGP also supported derivative observations as described in Section 
9.4 of [R&W](http://www.gaussianprocess.org/gpml/chapters/RW9.pdf )

<img width="866" alt="image" src="https://user-images.githubusercontent.com/4458890/152551937-7dc1175f-45a7-49e7-a95d-8442e085482a.png">

**Comment by dfm** [comment]
It does! (With some easy work.) Take a look at this tutorial and see if there's enough there for your purposes: https://tinygp.readthedocs.io/en/latest/tutorials/kernels.html#example-latent-gps-their-derivatives

If not, I'll happily provide more details.

**Comment by dfm** [comment]
On further thought, it might be useful to specifically add a tutorial about this - there are a few nice features to highlight.

**Comment by dfm** [comment]
I added a tutorial showing how to do this which will appear at https://tinygp.readthedocs.io/en/latest/tutorials/derivative.html shortly, as soon as the ReadTheDocs build finishes. Please re-open if you run into issues!

**Comment by cranmer** [comment]
Very nice, thank you!
