### ISSUE TITLE
Conditional sample

### ISSUE THREAD

**Issue by gmduvvuri** [dfm/tinygp#43]
Hello,

Just trying to figure out how to translate some george stuff to tinygp. How would I do a conditional sample draw from a GP? Trying the current sample function before and after conditioning the GP on data shows no change for the same PRNGKey.

Sorry if I am missing something obvious,
Girish.

**Comment by dfm** [comment]
There's no `sample_conditional` method in `tinygp`. For now, you would use:

```python
mu, cov = gp.predict(y, X_test)
y = jax.random.multivariate_normal(jax.random.PRNGKey(567), mu, cov)
```

After #32 is merged, it'll be simpler.

**Comment by dfm** [comment]
This is now documented in a few places, including [here](https://tinygp.readthedocs.io/en/latest/tutorials/intro.html) (the docs build is still running, but it'll be there soon), and will be included in the next release so I've closed this issue. Feel free to re-open if you feel that there is more to it!
