### ISSUE TITLE
Adding more details to deep kernel learning example

### ISSUE THREAD

**Issue by nipunbatra** [dfm/tinygp#61]
Hi 
I recently wrote a small example (heavily inspired by your example here In tinyGP) for [DKL for Pyro](https://github.com/prog-ml/prog-ml.github.io/blob/main/notebooks/gaussian_processes/pyro-deep-gp.ipynb)

I wonder if the tinyGP DKL example can be improved if we add (like the pyro code I wrote):

1. comparison with RBF (showing why DKL is better suited for discontinuities)
![Unknown](https://user-images.githubusercontent.com/60985/157402182-99423e5e-5ac2-4331-9d74-45ebb965651b.png)

2. showing the transformed features
![Unknown-2](https://user-images.githubusercontent.com/60985/157402216-1c0c0967-9cf7-4d29-b2b0-42c1daa2f226.png)

Please let me know how this looks. I or one of my students can make a small PR on this.

**Comment by dfm** [comment]
I agree that these would be great figures to add (I could have sworn that I had the transformed input plotted in an earlier version of that tutorial 🤔) and I'd be happy to review a PR like this!
