### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by benjaminpope** [dfm/tinygp#73]
This package is cool and we've already merged it into [ticktack](https://github.com/SharmaLlama/ticktack/), a package for carbon cycle modelling that we are using in a paper we are writing _right now_. (We weren't ridiculously quick - we swapped it in for celerite2 which we were already using).

How can we cite you?

**Comment by dfm** [comment]
Good question! I've got Zenodo set up to get a DOI on the next release, but we don't have anything yet. The next release should be soon, but I'm about to go on vacation so it'll be at least a week or two. Does that fit with your timeline?

**Comment by benjaminpope** [comment]
Oh yeah that’s fine - we will probably not submit for the best part of a month, and then there’ll be the review and proofs…

———————————————
Dr Benjamin Pope (he/him)
Lecturer in Astrophysics
University of Queensland
benjaminpope.github.io
________________________________

**Comment by dfm** [comment]
There is now a Zenodo citation and a link from the readme:

https://zenodo.org/record/6389738

**Comment by benjaminpope** [comment]
Great, thanks!
