### ISSUE TITLE
Sampling issue with `jax.random.multivariate_normal`

### ISSUE THREAD

**Issue by patel-zeel** [dfm/tinygp#75]
Sampling from a GP is giving unexpected results. For example, consider following code:

```py
import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
import tinygp

N = 1024

fig, ax = plt.subplots(3,3,figsize=(6.4*1.5, 4.8*1.5))
for seed in range(9):
  key = jax.random.PRNGKey(seed)
  x = 5 * jax.random.normal(key, shape=(N,1))
  kernel = 4 * tinygp.kernels.ExpSquared(scale=0.5)
  y = tinygp.GaussianProcess(kernel, x, diag=1.0).sample(key)
  ax.ravel()[seed].scatter(x, y, s=5);
```
This code generates the following output:
![image](https://user-images.githubusercontent.com/59758528/160297859-a63d660f-5557-46b3-8159-f8e5d34834eb.png)

If I replace `tinygp.GaussianProcess(kernel, x, diag=1.0).sample(key)` with `jax.random.multivariate_normal(key, jnp.zeros(N), kernel(x, x)+jnp.eye(N))`, I get the same result. But, if I change the sampling method as `jax.random.multivariate_normal(key, jnp.zeros(N), kernel(x, x)+jnp.eye(N), method='svd')`, I get drastically different results:

![image](https://user-images.githubusercontent.com/59758528/160298225-c4308a0a-e318-4fd0-acb8-746d7e2f6814.png)

**Comment by dfm** [comment]
That's because you're using the same key for both calls to random. You should always make sure to split the key:

```python
key = jax.random.PRNGKey(seed)
key1, key2 = jax.random.split(key)
x = 5 * jax.random.normal(key1, shape=(N,1))
kernel = 4 * tinygp.kernels.ExpSquared(scale=0.5)
y = tinygp.GaussianProcess(kernel, x, diag=1.0).sample(key2)
```

**Comment by patel-zeel** [comment]
Ah, I see. That seems like one of the causes. Thank you for the code. But why just changing the method from `cholesky` to `svd` is changing the samples?

**Comment by dfm** [comment]
There's no reason why using `svd` should give the same samples for the same `key`.

**Comment by dfm** [comment]
I should say: feel free to open an issue on the JAX repo if you don't like that, but this isn't a `tinygp` question!

**Comment by patel-zeel** [comment]
Sure, thank you!
