### ISSUE TITLE
Dynamic kernel combinations

### ISSUE THREAD

**Issue by patel-zeel** [dfm/tinygp#79]
Hi @dfm, I was exploring [automatic kernel combinations](https://arxiv.org/pdf/1302.4922.pdf) via an additive method following these simple rules mentioned in the linked paper:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/59758528/161062359-2cc9a653-fb4c-4621-8452-597dd04fd416.png">

I was following [this example](https://tinygp.readthedocs.io/en/stable/tutorials/quickstart.html) from the `tinygp` docs as it uses a similar dataset and kernel combinations. The challenge I am facing is managing the parameters for each kernel. During the exploration, the kernel combinations keep changing and thus we need to pass the `params` correctly to each kernel. As of now, I am trying to manage the `params` and kernel combinations with the functions given below which seems inefficient to me. Could you please suggest if there is a better way to manage the params and kernel combinations in such settings or if there is an entirely different `JAX` or `FLAX` way to do this efficiently?

```py
def generate_params(kernel_list, key):
    params = {'var':rand_gen(key)}
    for i, kernel in enumerate(kernel_list):
        key, key2 = jax.random.split(key, num=2)
        if kernel.__name__ == "ExpSquared":
            params.update({f'scale{i}':rand_gen(key)})
        elif kernel.__name__ == "ExpSineSquared":
            params.update({f'scale{i}':rand_gen(key), f'gamma{i}':rand_gen(key2)})
    return params

def build_kernel(params, ops, kernel_list): 
    final_kernel = 1
    for i, (kernel, op) in enumerate(zip(kernel_list, ops)):
        if kernel.__name__ == "ExpSquared":
            current_kernel = kernels.ExpSquared(scale=jnp.exp(params[f'scale{i}']))
        elif kernel.__name__ == "ExpSineSquared":
            current_kernel = kernels.ExpSineSquared(scale=jnp.exp(params[f'scale{i}']), gamma=jnp.exp(params[f'gamma{i}']))
        if op == 1:
            final_kernel = final_kernel * current_kernel
        elif op == 0:
            final_kernel = final_kernel + current_kernel
        else:
            raise ValueError()
    return jnp.exp(params['var']) * final_kernel
```

**Comment by dfm** [comment]
This looks pretty sensible to me. `tinygp` doesn't have any opinions about (or helpers for) handling complicated parameter structures so you can do whatever you want. It seems likely that you could build a more ergonomic interface using `flax` modules instead of implementing all of this manually, but I only have limited experience with that!

One comment: you'll probably also want to include an amplitude parameter for all of these terms (e.g. `jnp.exp(params[f'amp{i}']) * kernels.ExpSquared(scale=jnp.exp(params[f'scale{i}']))`) so that they don't all get included with unit weight.

**Comment by patel-zeel** [comment]
> This looks pretty sensible to me. `tinygp` doesn't have any opinions about (or helpers for) handling complicated parameter structures so you can do whatever you want. It seems likely that you could build a more ergonomic interface using `flax` modules instead of implementing all of this manually, but I only have limited experience with that!

Thank you for the suggestion, @dfm. I am very new to both `jax` and `flax` but I tried making each kernel into a self-contained `flax` model (coming from the PyTorch world), but I could not multiply those models to each other (without explicitly writing the `__mul__` method). Even after multiplication, the `GaussianProcess` class was having some problems with these flaxified kernels. Even if I could fix that somehow, I would still need to keep writing new `flax` models for any new kernel I want to include. Then I came across Pytrees and that made the process very simple. I noticed that you have designed the `tinygp.kernels` as Pytrees and thus I could write this simplistic end-to-end process without the need to deal with parameter dictionaries:

```py
import jax
import jax.numpy as jnp
import tinygp.kernels as kernels
from tinygp import GaussianProcess
import matplotlib.pyplot as plt

## Data: y = x ** 2
X = jnp.array([1., 3., 5.]).reshape(-1,1)
y = (X ** 2).flatten()

## Define a loss function
def loss_func(kernel, noise, X, y):
    gp = GaussianProcess(kernel, X, diag=noise)
    return -gp.log_probability(y)

## Transform the loss function into value_and_grad loss function
loss_grad_fn = jax.jit(jax.value_and_grad(loss_func, argnums=(0, 1)))

## Trainable Pytrees & parameters
kernel = (1.*kernels.ExpSquared(scale=1.) + 2. * kernels.ExpSineSquared(gamma=1.)) * kernels.Polynomial(order=1.)
noise = 0.1

# Learning rate
lr = 0.01

## Pretty old gradient descent!
losses = []
for i in range(20):
    loss_val, (kernel_grad, noise_grad) = loss_grad_fn(kernel, noise, X, y)
    losses.append(loss_val)
    (kernel, noise) = jax.tree_map(lambda val, grad: val - lr * grad, (kernel, noise), (kernel_grad, noise_grad))

## Plot the loss
plt.plot(losses, label='loss')
plt.xlabel('iterations')
plt.legend()

## Use trained parameters for inference
X_test = jnp.array([4.]).reshape(-1, 1)

gp = GaussianProcess(kernel, X, diag=noise)
pred_gp = gp.condition(y, X_test).gp

print(pred_gp.mean)
```
Output
```
[16.638536]
```
![image](https://user-images.githubusercontent.com/59758528/161376583-61dfcea9-b645-4a43-8a80-311668c7935f.png)

The above code also translates easily to `optax` settings after a few simple tweaks. Does this seem like a better way of training a `tinygp` model? If so, I can contribute this code as a tutorial notebook after applying some suggestions from you :)
 
> One comment: you'll probably also want to include an amplitude parameter for all of these terms (e.g. `jnp.exp(params[f'amp{i}']) * kernels.ExpSquared(scale=jnp.exp(params[f'scale{i}']))`) so that they don't all get included with unit weight.

Thanks for this suggestion :) I will modify my experiment accordingly.

**Comment by dfm** [comment]
Nice point about using kernels this way! I'm not so keen on adding an example of the dynamic kernel inference to the docs, but it would be nice to demonstrate this use of kernels as pytrees. My first thought is that it might be right to include it in the "custom kernels" tutorial, alongside a discussion of the built-in `dataclass` wrapper.

I'm going to close this issue, but can you open a new one referencing this with a suggestion for how you think it would be good to present this idea?
