### ISSUE TITLE
Discrepancy in returned log_likelihood between the **Celerite** kernel and the **ComplexTerm** from `celerite`

### ISSUE THREAD

**Issue by ywx649999311** [dfm/tinygp#87]
Hi @dfm 

I found a small difference in the log_likelihood value returned by the **Celerite** kernel of `tinygp` and the **ComplexTerm** from `celerite` (version 1). The difference is around 0.5 to 2, which is small. But I wonder if this is normal. I have tested it using a handful of kernel parameters and on both white noise time series and more structured ones. 

**Package versions:**
```
Python = 3.8.13
tinygp = 0.2.2
celerite = 0.4.2
```
**Operating System:** Ubuntu 20.04.4 LTS running within Docker on an iMax running Catalina

**How to reproduce:**
```python
# celerite
from celerite import GP, terms
import numpy as np

# jax/tingyp
import jax
from tinygp.kernels.quasisep import Celerite
from tinygp import kernels, GaussianProcess
jax.config.update("jax_enable_x64", True)
```

Simulate a white noise time series
```python
npts = 200
t_rand = np.sort(np.random.uniform(0, 3650, npts))
y_rand = np.random.normal(loc=0, scale=.3, size=(npts))
yerr_rand = np.random.normal(loc=0, scale=.03, size=(npts))
```

Evaluate the log_likelihood for a given set of a, b, c, d
```python
a, b, c, d = (7.20846339, 0.00018054, 5e-05, 0.16715561)

## tinygp
celerite_kernel = Celerite(a=a, b=b, c=c, d=d)
tinygp_gp = GaussianProcess(celerite_kernel, t_rand, diag=yerr_rand**2, mean=0.0)
tinygp_ll = tinygp_gp.log_probability(y_rand)

## celerite
complex_term = terms.ComplexTerm(np.log(a), np.log(b), np.log(c), np.log(d))
celerite_gp = GP(complex_term, mean=0.0)
celerite_gp.compute(t_rand, yerr_rand)
celerite_ll = celerite_gp.log_likelihood(y_rand)
```

Check if the return log_likelihood are the same
```python
assert np.allclose(tinygp_ll, celerite_ll)
```

Ideally I would expect the above test to pass, but it doesn't. There is an offset between `tinygp_ll` and `celerite_ll`, which is not a constant and varies based on the kernel parameters and the time series. 

Any clues? Thanks!

**Comment by dfm** [comment]
Thanks! I reproduce this issue and it is indeed puzzling. I haven't tested the `Celerite` kernel too thoroughly because I wouldn't generally recommend using it, so we should definitely get to the bottom of this. I'll see what I can find and report back!

**Comment by dfm** [comment]
I've fixed this over in #88 and I added some tests. One of the core matrices was incorrectly defined, but it should be good now!

**Comment by ywx649999311** [comment]
I played with a few different kernel parameters, your fix works! Thanks for the quick response!

**Comment by dfm** [comment]
Thanks for finding this issue!
